sudo: false
language: python
python: 3.6
cache: pip

env:
  - TOX_ENV=py36

install:
  - pip install --upgrade pip
  - pip install tox
  - python setup.py install

script:
  - python setup.py test
  - tox -e $TOX_ENV
